version: '3.8'

networks:
  db:
    labels:
      network.description: "Network for database services"
      
services:
  db:
    image: postgres:14.1-alpine
    container_name: WholesalerDb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432' 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
    networks:
      - db
      